### PR TITLE
Add default .stylelintrc during postinstall

### PR DESCRIPTION
**Pull request by sidforhbc**
This looks for a parent `node_modules` directory and, if it doesn't already exist, create a `.stylelintrc` file with `{ "extends": "@hbc/stylelint-config" }`.

### CODE REVIEW

**Comment by track0x1** [comment]
Looks great! I just want to see if theres a way we can avoid creating this file when we `npm i` in the repo itself. Otherwise we could just add it to `.gitignore`?

**Comment by sidforhbc** [comment]
Ah good call!

**Comment by track0x1** [comment]
Based off my 15 mins of research, it seems like the easiest solution is to just add to `.gitignore`. :-}

**Comment by sidforhbc** [comment]
Pfft!

**Comment by track0x1** [comment]
😄 this is good too! :)

**Pull request merged**
